name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linux
        run: |
          sudo apt update
          sudo apt install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev xorg-dev
          git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          python3 build.py --build