name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: linux
        run: |
          sudo apt install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev xorg-dev
          cargo build --verbose