name: Mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mac
        run: |
          git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          python3 build.py --build