name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.2
      - name: windows
        run: |
          py --version
          git clone https://github.com/vladasz/deploy
          py deploy/deploy.py
          py ~/.deps/build_tools/Build.py --prepare --ide --debug --vs19
          msbuild build/test_engine.sln
